language: node_js

sudo: required

node_js:
 - "4"
 - "6"
 - "8"

branches:
  only:
    - tech-sketch/1.7.0.plus

services:
 - rabbitmq
 - docker
 - mongodb

install:
 - npm install

before_install:
 - docker pull ansi/mosquitto
 - docker run -d -p 1883:1883 -l mosquitto ansi/mosquitto
 - npm install -g grunt-cli
